import * as stylex from '@stylexjs/stylex'

export const s = stylex.create({
  app: {
    minHeight: '100vh',
    backgroundColor: '#f5f6f8',
    color: '#172021',
  },
  shell: {
    minHeight: '100vh',
  },
  sidebar: {
    position: 'fixed',
    insetBlock: 0,
    insetInlineStart: 0,
    zIndex: 30,
    width: '244px',
    display: {
      default: 'flex',
      '@media (max-width: 880px)': 'none',
    },
    flexDirection: 'column',
    color: '#dce3e5',
    backgroundColor: '#11191c',
    borderInlineEnd: '1px solid #263135',
  },
  sidebarMobile: {
    display: 'flex',
    width: '272px',
    boxShadow: '18px 0 50px rgba(5, 12, 15, 0.24)',
  },
  sidebarBackdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 29,
    backgroundColor: 'rgba(7, 13, 16, 0.56)',
    backdropFilter: 'blur(3px)',
    display: {
      default: 'none',
      '@media (max-width: 880px)': 'block',
    },
    borderWidth: 0,
  },
  brandWrap: {
    height: '68px',
    paddingInline: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid #263135',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontWeight: 760,
    letterSpacing: '-0.03em',
    color: '#ffffff',
    fontSize: '18px',
  },
  brandMark: {
    display: 'grid',
    placeItems: 'center',
    width: '30px',
    height: '30px',
    borderRadius: '9px',
    color: '#ffffff',
    backgroundImage: 'linear-gradient(145deg, #7682ff, #4353e6 65%, #3340bd)',
    boxShadow: '0 5px 18px rgba(82, 96, 238, 0.35)',
  },
  envTag: {
    fontSize: '9px',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#829093',
    border: '1px solid #394448',
    borderRadius: '4px',
    paddingBlock: '3px',
    paddingInline: '5px',
  },
  workspace: {
    margin: '14px 12px 12px',
    padding: '10px',
    display: 'flex',
    alignItems: 'center',
    gap: '9px',
    color: '#eef2f3',
    backgroundColor: '#1a2428',
    border: '1px solid #2a363a',
    borderRadius: '10px',
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'background 150ms ease',
    ':hover': { backgroundColor: '#202d31' },
  },
  workspaceIcon: {
    width: '28px',
    height: '28px',
    display: 'grid',
    placeItems: 'center',
    borderRadius: '7px',
    backgroundColor: '#29363a',
    color: '#aeb8ff',
    flexShrink: 0,
  },
  workspaceText: { minWidth: 0, flex: 1 },
  workspaceName: {
    display: 'block',
    fontWeight: 650,
    fontSize: '12px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  workspaceOrg: {
    display: 'block',
    color: '#8c999d',
    fontSize: '10px',
    marginTop: '2px',
  },
  nav: {
    paddingInline: '10px',
    paddingBottom: '14px',
    flex: 1,
    overflowY: 'auto',
  },
  navLabel: {
    color: '#6f7d81',
    fontSize: '9px',
    fontWeight: 750,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    marginTop: '16px',
    marginBottom: '6px',
    paddingInline: '10px',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    minHeight: '38px',
    paddingBlock: '8px',
    paddingInline: '10px',
    gap: '10px',
    borderWidth: 0,
    borderRadius: '8px',
    backgroundColor: 'transparent',
    color: '#a9b4b7',
    cursor: 'pointer',
    textAlign: 'left',
    textDecoration: 'none',
    fontSize: '12px',
    fontWeight: 550,
    transition: 'color 140ms ease, background 140ms ease',
    ':hover': { color: '#f2f5f5', backgroundColor: '#1a2428' },
  },
  navItemActive: {
    color: '#ffffff',
    backgroundColor: '#253034',
    boxShadow: 'inset 3px 0 #7180ff',
  },
  navIcon: { width: '16px', height: '16px', flexShrink: 0 },
  navCount: {
    marginInlineStart: 'auto',
    minWidth: '20px',
    height: '18px',
    display: 'grid',
    placeItems: 'center',
    paddingInline: '5px',
    borderRadius: '9px',
    fontSize: '9px',
    fontWeight: 750,
    color: '#ffcbc4',
    backgroundColor: '#472c2b',
  },
  sidebarFooter: {
    padding: '12px',
    borderTop: '1px solid #263135',
  },
  statusLine: {
    padding: '9px 10px',
    borderRadius: '8px',
    backgroundColor: '#172421',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '10px',
    color: '#a9bab5',
  },
  statusDot: {
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    backgroundColor: '#45c68c',
    boxShadow: '0 0 0 3px rgba(69, 198, 140, .12)',
  },
  main: {
    marginInlineStart: {
      default: '244px',
      '@media (max-width: 880px)': 0,
    },
    minWidth: 0,
  },
  topbar: {
    position: 'sticky',
    top: 0,
    zIndex: 20,
    height: '68px',
    paddingInline: {
      default: '28px',
      '@media (max-width: 620px)': '14px',
    },
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    backgroundColor: 'rgba(255, 255, 255, 0.91)',
    backdropFilter: 'blur(16px)',
    borderBottom: '1px solid #e1e5e6',
  },
  mobileMenu: {
    display: {
      default: 'none',
      '@media (max-width: 880px)': 'grid',
    },
  },
  searchButton: {
    height: '36px',
    width: {
      default: 'min(420px, 40vw)',
      '@media (max-width: 620px)': '36px',
    },
    marginInlineEnd: 'auto',
    paddingInline: {
      default: '11px',
      '@media (max-width: 620px)': 0,
    },
    display: 'flex',
    alignItems: 'center',
    justifyContent: {
      default: 'flex-start',
      '@media (max-width: 620px)': 'center',
    },
    gap: '8px',
    border: '1px solid #dadddf',
    borderRadius: '9px',
    color: '#6d777a',
    backgroundColor: '#f8f9f9',
    cursor: 'pointer',
    fontSize: '12px',
    textAlign: 'left',
    ':hover': { borderColor: '#bbc2c4', backgroundColor: '#ffffff' },
  },
  searchText: {
    display: { default: 'inline', '@media (max-width: 620px)': 'none' },
  },
  shortcut: {
    marginInlineStart: 'auto',
    fontSize: '9px',
    color: '#7c8588',
    backgroundColor: '#ffffff',
    border: '1px solid #dde1e2',
    borderRadius: '5px',
    paddingBlock: '2px',
    paddingInline: '6px',
    display: { default: 'inline', '@media (max-width: 620px)': 'none' },
  },
  iconButton: {
    width: '36px',
    height: '36px',
    display: 'grid',
    placeItems: 'center',
    position: 'relative',
    border: '1px solid #dadddf',
    borderRadius: '9px',
    color: '#556063',
    backgroundColor: '#ffffff',
    cursor: 'pointer',
    transition: 'background 140ms ease, border 140ms ease',
    ':hover': { backgroundColor: '#f4f5f6', borderColor: '#bdc3c5' },
  },
  notificationDot: {
    position: 'absolute',
    top: '6px',
    right: '6px',
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    backgroundColor: '#f05b47',
    border: '2px solid #ffffff',
  },
  avatarButton: {
    padding: 0,
    borderWidth: 0,
    borderRadius: '50%',
    backgroundColor: 'transparent',
    cursor: 'pointer',
  },
  content: {
    paddingBlock: {
      default: '28px 52px',
      '@media (max-width: 620px)': '20px 36px',
    },
    paddingInline: {
      default: '28px',
      '@media (max-width: 620px)': '14px',
    },
    maxWidth: '1640px',
    marginInline: 'auto',
  },
  pageHeader: {
    display: 'flex',
    alignItems: { default: 'flex-end', '@media (max-width: 620px)': 'flex-start' },
    justifyContent: 'space-between',
    flexDirection: { default: 'row', '@media (max-width: 620px)': 'column' },
    gap: '16px',
    marginBottom: '22px',
  },
  eyebrow: {
    margin: 0,
    color: '#6c7779',
    fontSize: '10px',
    fontWeight: 750,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  },
  title: {
    margin: '4px 0 0',
    color: '#172021',
    fontSize: { default: '27px', '@media (max-width: 620px)': '23px' },
    lineHeight: 1.15,
    letterSpacing: '-0.035em',
    fontWeight: 730,
  },
  subtitle: {
    color: '#657073',
    fontSize: '12px',
    lineHeight: 1.5,
    margin: '6px 0 0',
    maxWidth: '720px',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '8px',
  },
  button: {
    minHeight: '36px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '7px',
    paddingBlock: '8px',
    paddingInline: '12px',
    border: '1px solid #d5dadd',
    borderRadius: '8px',
    color: '#3c474a',
    backgroundColor: '#ffffff',
    fontSize: '11px',
    fontWeight: 650,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'background 140ms ease, border 140ms ease, transform 140ms ease',
    ':hover': { backgroundColor: '#f6f7f7', borderColor: '#bfc6c8' },
    ':active': { transform: 'translateY(1px)' },
  },
  buttonPrimary: {
    color: '#ffffff',
    backgroundColor: '#4051d7',
    borderColor: '#4051d7',
    boxShadow: '0 4px 12px rgba(64, 81, 215, 0.18)',
    ':hover': { backgroundColor: '#3343c2', borderColor: '#3343c2' },
  },
  buttonDanger: {
    color: '#9d3328',
    backgroundColor: '#fff8f6',
    borderColor: '#f0c6c0',
    ':hover': { backgroundColor: '#fff0ed', borderColor: '#e5aaa1' },
  },
  buttonGhost: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  buttonSmall: {
    minHeight: '29px',
    paddingBlock: '5px',
    paddingInline: '9px',
    fontSize: '10px',
  },
  icon: { width: '15px', height: '15px', flexShrink: 0 },
  iconSm: { width: '13px', height: '13px', flexShrink: 0 },
  panel: {
    backgroundColor: '#ffffff',
    border: '1px solid #e0e4e5',
    borderRadius: '12px',
    boxShadow: '0 1px 2px rgba(20, 31, 34, 0.025)',
    minWidth: 0,
  },
  panelPad: { padding: { default: '18px', '@media (max-width: 620px)': '14px' } },
  panelHeader: {
    minHeight: '53px',
    paddingInline: '17px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '10px',
    borderBottom: '1px solid #e6e9ea',
  },
  panelTitle: {
    margin: 0,
    color: '#273235',
    fontSize: '12px',
    fontWeight: 720,
    letterSpacing: '-0.01em',
  },
  panelMeta: { color: '#7a8588', fontSize: '10px' },
  sectionTitle: {
    margin: '0 0 12px',
    color: '#283335',
    fontSize: '13px',
    fontWeight: 720,
    letterSpacing: '-0.01em',
  },
  muted: { color: '#758083' },
  tiny: { fontSize: '10px', lineHeight: 1.45 },
  small: { fontSize: '11px', lineHeight: 1.5 },
  bodyText: { color: '#4f5a5d', fontSize: '12px', lineHeight: 1.6 },
  mono: {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
    letterSpacing: '-0.02em',
  },
  strong: { fontWeight: 700, color: '#273235' },
  link: {
    color: '#3f51d3',
    backgroundColor: 'transparent',
    padding: 0,
    borderWidth: 0,
    cursor: 'pointer',
    textAlign: 'left',
    fontWeight: 630,
    ':hover': { color: '#2939b5', textDecoration: 'underline' },
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    minHeight: '21px',
    paddingBlock: '3px',
    paddingInline: '7px',
    borderRadius: '6px',
    fontSize: '9px',
    fontWeight: 750,
    letterSpacing: '0.025em',
    whiteSpace: 'nowrap',
    color: '#526064',
    backgroundColor: '#f0f2f3',
    border: '1px solid #e0e4e5',
  },
  badgeRed: { color: '#ad3529', backgroundColor: '#fff0ed', borderColor: '#f3c8c1' },
  badgeOrange: { color: '#965814', backgroundColor: '#fff6e8', borderColor: '#f1d9af' },
  badgeGreen: { color: '#237151', backgroundColor: '#eaf8f1', borderColor: '#c7ead9' },
  badgeBlue: { color: '#3453a3', backgroundColor: '#edf2ff', borderColor: '#d0dbfa' },
  badgeViolet: { color: '#6645ad', backgroundColor: '#f3efff', borderColor: '#ded2fb' },
  badgeGray: { color: '#5f6b6e', backgroundColor: '#f3f5f5', borderColor: '#e1e5e6' },
  badgeDark: { color: '#eef2f3', backgroundColor: '#293437', borderColor: '#293437' },
  dot: { width: '6px', height: '6px', borderRadius: '50%', backgroundColor: 'currentColor' },
  avatar: {
    width: '30px',
    height: '30px',
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
    borderRadius: '50%',
    fontSize: '9px',
    fontWeight: 760,
    letterSpacing: '-0.01em',
    border: '2px solid #ffffff',
    color: '#3d487c',
    backgroundColor: '#e4e8ff',
  },
  avatarSmall: { width: '24px', height: '24px', fontSize: '8px', borderWidth: '1.5px' },
  avatarLarge: { width: '42px', height: '42px', fontSize: '11px' },
  avatarBlue: { color: '#235e91', backgroundColor: '#dceefa' },
  avatarGreen: { color: '#246d54', backgroundColor: '#ddf3e9' },
  avatarAmber: { color: '#865515', backgroundColor: '#faebce' },
  avatarRose: { color: '#8e4559', backgroundColor: '#fae2e8' },
  avatarSlate: { color: '#4b5d65', backgroundColor: '#e1e8eb' },
  avatarStack: { display: 'flex' },
  avatarOverlap: { marginInlineStart: '-7px' },
  divider: { height: '1px', backgroundColor: '#e6e9ea', borderWidth: 0, marginBlock: '14px' },
  grid2: {
    display: 'grid',
    gridTemplateColumns: { default: 'repeat(2, minmax(0, 1fr))', '@media (max-width: 700px)': '1fr' },
    gap: '14px',
  },
  grid3: {
    display: 'grid',
    gridTemplateColumns: { default: 'repeat(3, minmax(0, 1fr))', '@media (max-width: 1050px)': 'repeat(2, minmax(0, 1fr))', '@media (max-width: 620px)': '1fr' },
    gap: '14px',
  },
  grid4: {
    display: 'grid',
    gridTemplateColumns: { default: 'repeat(4, minmax(0, 1fr))', '@media (max-width: 1180px)': 'repeat(2, minmax(0, 1fr))', '@media (max-width: 620px)': '1fr' },
    gap: '12px',
  },
  metric: {
    padding: '15px 16px',
    minWidth: 0,
  },
  metricLabel: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '8px',
    color: '#687477',
    fontSize: '10px',
    fontWeight: 620,
  },
  metricValue: {
    color: '#1c2729',
    fontSize: '25px',
    lineHeight: 1.15,
    fontWeight: 740,
    letterSpacing: '-0.045em',
    marginTop: '8px',
  },
  metricFooter: {
    marginTop: '7px',
    color: '#7b8588',
    fontSize: '9px',
    lineHeight: 1.4,
  },
  positive: { color: '#277958' },
  negative: { color: '#ba4335' },
  neutral: { color: '#566367' },
  tableWrap: { overflowX: 'auto' },
  table: { width: '100%', borderCollapse: 'collapse', minWidth: '760px' },
  tableCompact: { minWidth: '620px' },
  th: {
    height: '38px',
    paddingInline: '14px',
    color: '#7c878a',
    backgroundColor: '#fafbfb',
    borderBottom: '1px solid #e4e7e8',
    fontSize: '9px',
    fontWeight: 720,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    textAlign: 'left',
    whiteSpace: 'nowrap',
  },
  td: {
    paddingBlock: '12px',
    paddingInline: '14px',
    borderBottom: '1px solid #edf0f0',
    color: '#536063',
    fontSize: '10px',
    verticalAlign: 'middle',
  },
  trClickable: {
    cursor: 'pointer',
    transition: 'background 120ms ease',
    ':hover': { backgroundColor: '#fafbfe' },
  },
  rowPrimary: { color: '#263235', fontSize: '11px', fontWeight: 650, lineHeight: 1.35 },
  rowSecondary: { color: '#818b8e', fontSize: '9px', marginTop: '3px' },
  toolbar: {
    padding: '12px',
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '8px',
    borderBottom: '1px solid #e5e8e9',
  },
  inputWrap: {
    position: 'relative',
    flex: { default: '1 1 220px', '@media (max-width: 620px)': '1 1 100%' },
    minWidth: 0,
  },
  inputIcon: {
    position: 'absolute',
    left: '10px',
    top: '50%',
    transform: 'translateY(-50%)',
    width: '14px',
    height: '14px',
    color: '#899396',
    pointerEvents: 'none',
  },
  input: {
    width: '100%',
    height: '36px',
    paddingInline: '11px',
    border: '1px solid #d8ddde',
    borderRadius: '8px',
    color: '#293537',
    backgroundColor: '#ffffff',
    fontSize: '11px',
    ':focus': { borderColor: '#7280ed', boxShadow: '0 0 0 3px rgba(80, 98, 222, .11)' },
    '::placeholder': { color: '#9ba3a5' },
  },
  inputWithIcon: { paddingInlineStart: '32px' },
  select: {
    minWidth: '122px',
    height: '36px',
    paddingInline: '10px 30px',
    border: '1px solid #d8ddde',
    borderRadius: '8px',
    color: '#4d595c',
    backgroundColor: '#ffffff',
    fontSize: '10px',
    fontWeight: 600,
    cursor: 'pointer',
    ':focus': { borderColor: '#7280ed', boxShadow: '0 0 0 3px rgba(80, 98, 222, .11)' },
  },
  segmented: {
    display: 'inline-flex',
    padding: '3px',
    gap: '2px',
    border: '1px solid #dfe3e4',
    borderRadius: '8px',
    backgroundColor: '#f5f6f7',
  },
  segment: {
    minHeight: '27px',
    paddingInline: '9px',
    borderWidth: 0,
    borderRadius: '5px',
    color: '#788285',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    fontSize: '9px',
    fontWeight: 650,
  },
  segmentActive: {
    color: '#313d40',
    backgroundColor: '#ffffff',
    boxShadow: '0 1px 3px rgba(24, 37, 40, .11)',
  },
  emptyFilter: { padding: '48px 20px', textAlign: 'center', color: '#768184', fontSize: '11px' },
  inline: { display: 'flex', alignItems: 'center', gap: '8px', minWidth: 0 },
  inlineBetween: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '10px', minWidth: 0 },
  wrap: { display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' },
  column: { display: 'flex', flexDirection: 'column' },
  gap4: { gap: '4px' },
  gap8: { gap: '8px' },
  gap12: { gap: '12px' },
  gap16: { gap: '16px' },
  marginTop8: { marginTop: '8px' },
  marginTop12: { marginTop: '12px' },
  marginTop16: { marginTop: '16px' },
  marginTop20: { marginTop: '20px' },
  marginBottom12: { marginBottom: '12px' },
  noMargin: { margin: 0 },
  grow: { flex: 1, minWidth: 0 },
  hideMobile: { display: { default: 'initial', '@media (max-width: 620px)': 'none' } },
  overlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 80,
    display: 'flex',
    alignItems: { default: 'flex-start', '@media (max-width: 620px)': 'flex-end' },
    justifyContent: 'center',
    paddingBlock: { default: '10vh', '@media (max-width: 620px)': 0 },
    paddingInline: { default: '16px', '@media (max-width: 620px)': 0 },
    backgroundColor: 'rgba(15, 24, 27, .52)',
    backdropFilter: 'blur(5px)',
  },
  modal: {
    width: 'min(620px, 100%)',
    maxHeight: { default: '80vh', '@media (max-width: 620px)': '92vh' },
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    borderRadius: { default: '14px', '@media (max-width: 620px)': '16px 16px 0 0' },
    backgroundColor: '#ffffff',
    border: '1px solid rgba(255,255,255,.6)',
    boxShadow: '0 28px 90px rgba(14, 24, 27, .28)',
  },
  modalWide: { width: 'min(760px, 100%)' },
  modalHeader: {
    minHeight: '59px',
    paddingInline: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    borderBottom: '1px solid #e4e8e9',
  },
  modalBody: { padding: '18px', overflowY: 'auto' },
  modalFooter: {
    minHeight: '60px',
    paddingInline: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: '8px',
    borderTop: '1px solid #e4e8e9',
    backgroundColor: '#fafbfb',
  },
  commandModal: {
    width: 'min(650px, 100%)',
    maxHeight: '72vh',
  },
  commandInputWrap: {
    height: '60px',
    paddingInline: '18px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    borderBottom: '1px solid #e4e8e9',
  },
  commandInput: {
    flex: 1,
    height: '58px',
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: '#253033',
    fontSize: '15px',
    '::placeholder': { color: '#929c9f' },
  },
  commandResults: { padding: '8px', overflowY: 'auto' },
  commandGroup: {
    padding: '8px 10px 5px',
    color: '#899295',
    fontSize: '9px',
    fontWeight: 720,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  commandItem: {
    width: '100%',
    padding: '10px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    borderWidth: 0,
    borderRadius: '8px',
    backgroundColor: 'transparent',
    color: '#384447',
    textAlign: 'left',
    cursor: 'pointer',
    ':hover': { backgroundColor: '#f1f3f7' },
  },
  commandIcon: {
    width: '32px',
    height: '32px',
    display: 'grid',
    placeItems: 'center',
    borderRadius: '8px',
    color: '#5a69d9',
    backgroundColor: '#eef0ff',
    flexShrink: 0,
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: { default: 'repeat(2, minmax(0, 1fr))', '@media (max-width: 560px)': '1fr' },
    gap: '14px',
  },
  field: { display: 'flex', flexDirection: 'column', gap: '6px', minWidth: 0 },
  fieldFull: { gridColumn: { default: '1 / -1', '@media (max-width: 560px)': 'auto' } },
  label: { color: '#4f5b5e', fontSize: '10px', fontWeight: 680 },
  textarea: {
    width: '100%',
    minHeight: '92px',
    resize: 'vertical',
    padding: '10px 11px',
    border: '1px solid #d8ddde',
    borderRadius: '8px',
    color: '#293537',
    backgroundColor: '#ffffff',
    fontSize: '11px',
    lineHeight: 1.5,
    ':focus': { borderColor: '#7280ed', boxShadow: '0 0 0 3px rgba(80, 98, 222, .11)' },
  },
  hint: { color: '#899295', fontSize: '9px', lineHeight: 1.4 },
  error: { color: '#b63d31', fontSize: '9px', fontWeight: 620 },
  toast: {
    position: 'fixed',
    right: { default: '22px', '@media (max-width: 620px)': '14px' },
    bottom: '20px',
    zIndex: 100,
    maxWidth: '360px',
    padding: '12px 14px',
    display: 'flex',
    alignItems: 'center',
    gap: '9px',
    color: '#ecf7f2',
    backgroundColor: '#1f332c',
    border: '1px solid #3b5a4f',
    borderRadius: '10px',
    boxShadow: '0 14px 36px rgba(12, 25, 20, .22)',
    fontSize: '11px',
    fontWeight: 620,
  },
  fab: {
    position: 'fixed',
    right: '18px',
    bottom: '18px',
    zIndex: 19,
    width: '42px',
    height: '42px',
    display: 'grid',
    placeItems: 'center',
    borderWidth: 0,
    borderRadius: '13px',
    color: '#ffffff',
    backgroundColor: '#4051d7',
    boxShadow: '0 8px 24px rgba(64,81,215,.3)',
    cursor: 'pointer',
    transition: 'transform 140ms ease, background 140ms ease',
    ':hover': { backgroundColor: '#3343c2', transform: 'translateY(-2px)' },
    ':active': { transform: 'translateY(0)' },
  },
  popover: {
    position: 'fixed',
    zIndex: 60,
    top: '59px',
    right: { default: '24px', '@media (max-width: 620px)': '8px' },
    width: { default: '380px', '@media (max-width: 620px)': 'calc(100vw - 16px)' },
    maxHeight: 'min(640px, calc(100vh - 76px))',
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    border: '1px solid #dce1e2',
    borderRadius: '12px',
    boxShadow: '0 20px 58px rgba(19, 31, 35, .18)',
  },
  notificationItem: {
    position: 'relative',
    padding: '13px 15px',
    display: 'flex',
    gap: '10px',
    borderBottom: '1px solid #edf0f0',
  },
  notificationUnread: { backgroundColor: '#f7f8ff' },
  notificationUnreadDot: {
    position: 'absolute',
    top: '18px',
    right: '13px',
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    backgroundColor: '#5667e7',
  },
  notificationGlyph: {
    width: '30px',
    height: '30px',
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
    borderRadius: '8px',
    color: '#5667d8',
    backgroundColor: '#edf0ff',
  },
  tabs: {
    display: 'flex',
    gap: '2px',
    overflowX: 'auto',
    borderBottom: '1px solid #dfe3e4',
    marginBottom: '18px',
  },
  tab: {
    position: 'relative',
    paddingBlock: '10px',
    paddingInline: '12px',
    borderWidth: 0,
    color: '#6d787b',
    backgroundColor: 'transparent',
    fontSize: '10px',
    fontWeight: 650,
    whiteSpace: 'nowrap',
    cursor: 'pointer',
    ':hover': { color: '#334043' },
  },
  tabActive: {
    color: '#3546c7',
    boxShadow: 'inset 0 -2px #5061df',
  },
  progressTrack: {
    width: '100%',
    height: '5px',
    overflow: 'hidden',
    borderRadius: '3px',
    backgroundColor: '#e8ebec',
  },
  progressFill: { height: '100%', borderRadius: '3px', backgroundColor: '#5062dc' },
  checkbox: {
    width: '16px',
    height: '16px',
    accentColor: '#4354d8',
    cursor: 'pointer',
    flexShrink: 0,
  },
})

export const p = stylex.create({
  detailToolbar: {
    display: 'flex',
    alignItems: { default: 'center', '@media (max-width: 700px)': 'flex-start' },
    justifyContent: 'space-between',
    flexDirection: { default: 'row', '@media (max-width: 700px)': 'column' },
    gap: '10px',
  },
  overviewGrid: {
    display: 'grid',
    gridTemplateColumns: { default: 'minmax(0, 1.65fr) minmax(300px, .85fr)', '@media (max-width: 1100px)': '1fr' },
    gap: '14px',
  },
  incidentHero: {
    padding: { default: '20px', '@media (max-width: 620px)': '16px' },
    backgroundImage: 'linear-gradient(135deg, #fff 0%, #fff 62%, #fff3f0 100%)',
    borderColor: '#edcec8',
  },
  incidentHeroTop: {
    display: 'flex',
    alignItems: { default: 'flex-start', '@media (max-width: 620px)': 'stretch' },
    justifyContent: 'space-between',
    flexDirection: { default: 'row', '@media (max-width: 620px)': 'column' },
    gap: '14px',
  },
  incidentTitle: {
    margin: '8px 0 8px',
    color: '#232d30',
    fontSize: { default: '18px', '@media (max-width: 620px)': '16px' },
    fontWeight: 730,
    lineHeight: 1.32,
    letterSpacing: '-0.025em',
  },
  incidentStats: {
    display: 'grid',
    gridTemplateColumns: { default: 'repeat(4, minmax(0, 1fr))', '@media (max-width: 620px)': 'repeat(2, minmax(0, 1fr))' },
    gap: '1px',
    marginTop: '18px',
    overflow: 'hidden',
    backgroundColor: '#e5e8e9',
    border: '1px solid #e5e8e9',
    borderRadius: '9px',
  },
  incidentStat: { padding: '11px 12px', backgroundColor: 'rgba(255,255,255,.78)' },
  statLabel: { color: '#7e888b', fontSize: '9px', marginBottom: '4px' },
  statValue: { color: '#293436', fontSize: '11px', fontWeight: 680 },
  attention: {
    padding: '12px',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    borderRadius: '9px',
    color: '#72451a',
    backgroundColor: '#fff8e9',
    border: '1px solid #f0dfbd',
  },
  healthBar: {
    height: '9px',
    display: 'flex',
    overflow: 'hidden',
    borderRadius: '5px',
    backgroundColor: '#e8ebec',
  },
  healthCritical: { width: '8.5%', backgroundColor: '#e15a4a' },
  healthDegraded: { width: '21.3%', backgroundColor: '#e9a33f' },
  healthHealthy: { width: '70.2%', backgroundColor: '#43b885' },
  healthLegend: { display: 'flex', flexWrap: 'wrap', gap: '14px', marginTop: '10px' },
  legendItem: { display: 'flex', alignItems: 'center', gap: '5px', color: '#6d787b', fontSize: '9px' },
  chart: { width: '100%', height: '150px', overflow: 'visible' },
  chartGrid: { stroke: '#e9ecec', strokeWidth: 1 },
  chartLine: { fill: 'none', stroke: '#5364dc', strokeWidth: 2.2, strokeLinecap: 'round', strokeLinejoin: 'round' },
  chartArea: { fill: 'url(#trendFill)' },
  chartDot: { fill: '#ffffff', stroke: '#5364dc', strokeWidth: 2 },
  deployRow: {
    paddingBlock: '11px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    borderBottom: '1px solid #edf0f0',
  },
  deployRail: { width: '3px', height: '35px', borderRadius: '2px', backgroundColor: '#52b886', flexShrink: 0 },
  deployRailDanger: { backgroundColor: '#e15a4a' },
  deployRailWarn: { backgroundColor: '#dfa03e' },
  personRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    paddingBlock: '10px',
    borderBottom: '1px solid #edf0f0',
  },
  pageSplit: {
    display: 'grid',
    gridTemplateColumns: { default: 'minmax(0, 1fr) 310px', '@media (max-width: 1080px)': '1fr' },
    gap: '14px',
    alignItems: 'start',
  },
  incidentLayout: {
    display: 'grid',
    gridTemplateColumns: { default: 'minmax(0, 1fr) 330px', '@media (max-width: 1120px)': '1fr' },
    gap: '14px',
    alignItems: 'start',
  },
  incidentBanner: {
    padding: { default: '18px 20px', '@media (max-width: 620px)': '15px' },
    borderColor: '#efc6c0',
    backgroundImage: 'linear-gradient(110deg, #fff 0%, #fff 60%, #fff2ef 100%)',
  },
  incidentBannerTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    flexDirection: { default: 'row', '@media (max-width: 760px)': 'column' },
    gap: '14px',
  },
  detailTitle: {
    margin: '7px 0 8px',
    color: '#1e292b',
    fontSize: { default: '22px', '@media (max-width: 620px)': '18px' },
    lineHeight: 1.25,
    fontWeight: 740,
    letterSpacing: '-0.035em',
  },
  propertyGrid: {
    display: 'grid',
    gridTemplateColumns: { default: 'repeat(5, minmax(0, 1fr))', '@media (max-width: 760px)': 'repeat(2, minmax(0, 1fr))' },
    gap: '12px',
    marginTop: '17px',
  },
  propertyLabel: { color: '#818b8e', fontSize: '9px', marginBottom: '5px' },
  propertyValue: { color: '#344043', fontSize: '10px', fontWeight: 650, lineHeight: 1.4 },
  timeline: { padding: '5px 17px 14px' },
  timelineItem: {
    position: 'relative',
    display: 'grid',
    gridTemplateColumns: { default: '58px 26px minmax(0, 1fr)', '@media (max-width: 520px)': '48px 22px minmax(0, 1fr)' },
    minHeight: '76px',
  },
  timelineTime: { paddingTop: '16px', color: '#7b8588', fontSize: '9px', fontWeight: 620, whiteSpace: 'nowrap' },
  timelineTrack: { position: 'relative', display: 'flex', justifyContent: 'center' },
  timelineLine: { position: 'absolute', top: 0, bottom: 0, width: '1px', backgroundColor: '#dfe4e5' },
  timelineDot: { position: 'relative', zIndex: 1, marginTop: '17px', width: '9px', height: '9px', borderRadius: '50%', backgroundColor: '#7582e7', border: '2px solid #ffffff', boxShadow: '0 0 0 1px #bec6f8' },
  timelineDotAlert: { backgroundColor: '#e15c4d', boxShadow: '0 0 0 1px #efbdb6' },
  timelineDotDeploy: { backgroundColor: '#d59435', boxShadow: '0 0 0 1px #e8c993' },
  timelineDotSystem: { backgroundColor: '#829094', boxShadow: '0 0 0 1px #ccd2d4' },
  timelineContent: { paddingBlock: '13px', paddingInlineStart: '8px', borderBottom: '1px solid #edf0f0', minWidth: 0 },
  timelineTitle: { color: '#344043', fontSize: '10px', fontWeight: 680, lineHeight: 1.4 },
  timelineBody: { marginTop: '4px', color: '#737e81', fontSize: '10px', lineHeight: 1.48 },
  composer: { padding: '14px 17px', backgroundColor: '#fafbfb', borderTop: '1px solid #e5e8e9' },
  composerBox: { display: 'flex', alignItems: 'flex-start', gap: '9px' },
  composerInput: { minHeight: '66px' },
  taskRow: { paddingBlock: '10px', display: 'flex', alignItems: 'flex-start', gap: '9px', borderBottom: '1px solid #edf0f0' },
  taskDone: { color: '#8a9396', textDecoration: 'line-through' },
  serviceImpactRow: { paddingBlock: '10px', display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) auto', gap: '8px', borderBottom: '1px solid #edf0f0' },
  rateCard: { padding: '15px', color: '#ffffff', backgroundColor: '#222c2f', borderRadius: '10px' },
  rateValue: { fontSize: '30px', fontWeight: 730, letterSpacing: '-0.05em', margin: '6px 0 4px' },
  miniChart: { width: '100%', height: '58px', marginTop: '8px' },
  servicesGrid: { display: 'grid', gridTemplateColumns: { default: 'repeat(3, minmax(0, 1fr))', '@media (max-width: 1200px)': 'repeat(2, minmax(0, 1fr))', '@media (max-width: 660px)': '1fr' }, gap: '12px' },
  serviceCard: { padding: '15px', cursor: 'pointer', transition: 'border 150ms ease, transform 150ms ease, box-shadow 150ms ease', ':hover': { borderColor: '#bec6e9', transform: 'translateY(-1px)', boxShadow: '0 7px 22px rgba(29, 39, 72, .07)' } },
  serviceIcon: { width: '34px', height: '34px', display: 'grid', placeItems: 'center', borderRadius: '9px', color: '#5060d3', backgroundColor: '#eef0ff' },
  serviceHealthLine: { marginTop: '13px', paddingTop: '11px', borderTop: '1px solid #edf0f0', display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '8px' },
  serviceStatLabel: { color: '#899295', fontSize: '8px', textTransform: 'uppercase', letterSpacing: '.05em' },
  serviceStatValue: { color: '#3b474a', fontSize: '10px', fontWeight: 680, marginTop: '3px' },
  serviceHeader: { padding: '19px', display: 'flex', alignItems: { default: 'center', '@media (max-width: 620px)': 'flex-start' }, justifyContent: 'space-between', flexDirection: { default: 'row', '@media (max-width: 620px)': 'column' }, gap: '14px' },
  relationship: { display: 'grid', gridTemplateColumns: { default: '1fr 90px 1fr', '@media (max-width: 580px)': '1fr' }, alignItems: 'center', gap: '10px', padding: '16px' },
  relationColumn: { display: 'flex', flexDirection: 'column', gap: '8px' },
  relationCard: { padding: '10px', display: 'flex', alignItems: 'center', gap: '8px', border: '1px solid #e0e4e5', borderRadius: '8px', color: '#3d494c', backgroundColor: '#fafbfb', fontSize: '10px', fontWeight: 650 },
  relationCenter: { display: 'grid', placeItems: 'center', gap: '5px', color: '#7a8588', fontSize: '8px', textTransform: 'uppercase', letterSpacing: '.06em' },
  selectedService: { color: '#ffffff', backgroundColor: '#4051d7', borderColor: '#4051d7' },
  schedule: { overflowX: 'auto' },
  scheduleGrid: { minWidth: '760px', display: 'grid', gridTemplateColumns: '150px repeat(7, minmax(82px, 1fr))' },
  scheduleCell: { minHeight: '55px', padding: '9px', borderInlineEnd: '1px solid #e8ebec', borderBottom: '1px solid #e8ebec', fontSize: '9px', color: '#647073' },
  scheduleHeader: { minHeight: '45px', backgroundColor: '#fafbfb', color: '#6e797c', fontWeight: 680 },
  shiftPrimary: { minHeight: '34px', borderRadius: '7px', padding: '7px', color: '#33439b', backgroundColor: '#e9edff', border: '1px solid #d3dafb' },
  shiftSecondary: { minHeight: '34px', borderRadius: '7px', padding: '7px', color: '#296b52', backgroundColor: '#e8f6ef', border: '1px solid #cce8da' },
  chartLayout: { display: 'grid', gridTemplateColumns: { default: 'minmax(0, 1.5fr) minmax(260px, .7fr)', '@media (max-width: 950px)': '1fr' }, gap: '14px' },
  barChart: { height: '190px', display: 'flex', alignItems: 'flex-end', gap: { default: '10px', '@media (max-width: 520px)': '5px' }, paddingTop: '20px' },
  barCol: { height: '100%', flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'flex-end', gap: '6px' },
  bar: { width: '70%', minWidth: '10px', borderRadius: '4px 4px 1px 1px', backgroundColor: '#6472df' },
  barAccent: { backgroundColor: '#e37a58' },
  barLabel: { color: '#7d888a', fontSize: '8px' },
  donutWrap: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '22px', paddingBlock: '18px' },
  donut: { width: '118px', height: '118px', transform: 'rotate(-90deg)' },
  rankingRow: { display: 'grid', gridTemplateColumns: '20px minmax(0, 1fr) 45px', alignItems: 'center', gap: '8px', paddingBlock: '9px', borderBottom: '1px solid #edf0f0' },
  rank: { color: '#929b9e', fontSize: '9px', fontWeight: 700 },
  compactBar: { height: '4px', marginTop: '5px', borderRadius: '2px', backgroundColor: '#e7eaeb', overflow: 'hidden' },
  compactBarFill: { height: '100%', backgroundColor: '#6876df', borderRadius: '2px' },
  postmortemCard: { padding: '16px', cursor: 'pointer', ':hover': { borderColor: '#c4cbea', boxShadow: '0 5px 18px rgba(28, 39, 74, .06)' } },
  document: { padding: { default: '27px 32px', '@media (max-width: 620px)': '18px 15px' } },
  docSection: { paddingBlock: '19px', borderBottom: '1px solid #e7eaeb' },
  docHeading: { margin: '0 0 9px', color: '#263134', fontSize: '14px', fontWeight: 720, letterSpacing: '-.015em' },
  docText: { margin: 0, color: '#566164', fontSize: '11px', lineHeight: 1.7 },
  quote: { margin: '12px 0 0', padding: '11px 13px', borderInlineStart: '3px solid #6b78dd', color: '#525f63', backgroundColor: '#f6f7fc', fontSize: '10px', lineHeight: 1.6 },
  editArea: { width: '100%', minHeight: '130px', border: '1px solid #ccd3d5', borderRadius: '8px', padding: '10px', color: '#4b575a', fontSize: '11px', lineHeight: 1.6, resize: 'vertical' },
  teamHero: { padding: { default: '22px', '@media (max-width: 620px)': '16px' }, backgroundImage: 'linear-gradient(135deg, #ffffff 55%, #f0f2ff)' },
  memberGrid: { display: 'grid', gridTemplateColumns: { default: 'repeat(2, minmax(0, 1fr))', '@media (max-width: 580px)': '1fr' }, gap: '8px' },
  memberCard: { padding: '11px', display: 'flex', alignItems: 'center', gap: '10px', border: '1px solid #e4e7e8', borderRadius: '9px', backgroundColor: '#fafbfb' },
  settingsLayout: { display: 'grid', gridTemplateColumns: { default: '190px minmax(0, 1fr)', '@media (max-width: 700px)': '1fr' }, gap: '18px', alignItems: 'start' },
  settingsNav: { position: { default: 'sticky', '@media (max-width: 700px)': 'static' }, top: '88px', display: { default: 'flex', '@media (max-width: 700px)': 'grid' }, gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', flexDirection: 'column', gap: '4px' },
  settingsNavItem: { padding: '9px 10px', borderWidth: 0, borderRadius: '7px', backgroundColor: 'transparent', color: '#647073', textAlign: 'left', fontSize: '10px', fontWeight: 620, cursor: 'pointer', ':hover': { backgroundColor: '#eceff0' } },
  settingsNavActive: { color: '#3546c6', backgroundColor: '#e9ecff' },
  integrationGrid: { display: 'grid', gridTemplateColumns: { default: 'repeat(2, minmax(0, 1fr))', '@media (max-width: 560px)': '1fr' }, gap: '9px' },
  integrationCard: { padding: '12px', display: 'flex', alignItems: 'center', gap: '10px', border: '1px solid #e0e4e5', borderRadius: '9px' },
  integrationIcon: { width: '34px', height: '34px', display: 'grid', placeItems: 'center', borderRadius: '9px', backgroundColor: '#222c2f', color: '#ffffff', fontSize: '11px', fontWeight: 740 },
  toggle: { width: '34px', height: '19px', borderWidth: 0, borderRadius: '10px', backgroundColor: '#cfd5d7', padding: '2px', cursor: 'pointer' },
  toggleOn: { backgroundColor: '#4d5ed9' },
  toggleThumb: { width: '15px', height: '15px', borderRadius: '50%', backgroundColor: '#ffffff', boxShadow: '0 1px 2px rgba(0,0,0,.2)', transform: 'translateX(0)', transition: 'transform 140ms ease' },
  toggleThumbOn: { transform: 'translateX(15px)' },
})
