import * as stylex from '@stylexjs/stylex';
import { useState } from 'react';
import { ArrowDownWideNarrow, Clock3, Columns3, List, Plus, ShieldAlert } from 'lucide-react';
import { services, type Incident } from '../data/model';
import { useStore } from '../state/store';
import { useActions } from '../state/actions';
import { AppLink, AvatarGroup, Badge, Button, EmptyResults, PageHeader, Panel, Person, SearchInput, Select, Status, Tabs, ui } from '../components/ui';
const s = stylex.create({ board: { display: 'grid', gridTemplateColumns: 'repeat(4, minmax(240px, 1fr))', gap: 15, overflowX: 'auto', paddingBottom: 10 }, column: { backgroundColor: '#eff3f3', padding: 12, borderRadius: 8, minHeight: 250 }, card: { backgroundColor: '#fff', padding: 16, border: '1px solid #e2e8e5', borderRadius: 7, marginTop: 12 }, title: { fontSize: 13, fontWeight: 600, lineHeight: 1.6, margin: '12px 0' }, foot: { padding: '15px 20px', fontSize: 11, color: '#8e9b94', display: 'flex', justifyContent: 'space-between' } });
export function Incidents() {
  const { data } = useStore(); const { createIncident } = useActions();
  const [query, setQuery] = useState(''); const [severity, setSeverity] = useState('All severities'); const [status, setStatus] = useState('All statuses'); const [tab, setTab] = useState('All incidents'); const [sort, setSort] = useState('Newest first'); const [view, setView] = useState('list');
  const active = data.incidents.filter(i => i.status !== 'Resolved');
  const filtered = data.incidents.filter(i => `${i.title} ${i.id} ${i.services.join(' ')} ${i.commander}`.toLowerCase().includes(query.toLowerCase()) && (severity === 'All severities' || i.severity === severity) && (status === 'All statuses' || i.status === status) && (tab === 'All incidents' || (tab === 'Active' ? i.status !== 'Resolved' : i.status === 'Resolved'))).sort((a, b) => sort === 'Severity' ? a.severity.localeCompare(b.severity) : sort === 'Oldest first' ? a.id.localeCompare(b.id) : b.id.localeCompare(a.id));
  return <><PageHeader title="Incidents" description="Coordinate your response. Restore what matters." actions={<Button variant="primary" onClick={() => createIncident()}><Plus size={15} />Create incident</Button>} /><Tabs value={tab} onChange={setTab} tabs={[{ label: 'All incidents', count: data.incidents.length }, { label: 'Active', count: active.length }, { label: 'Resolved', count: data.incidents.length - active.length }]} /><div {...stylex.props(ui.toolbar)}><div {...stylex.props(ui.row, ui.wrap)}><SearchInput placeholder="Search incidents…" value={query} onChange={setQuery} /><Select aria-label="Filter by severity" value={severity} onChange={e => setSeverity(e.target.value)}>{['All severities', 'SEV0', 'SEV1', 'SEV2', 'SEV3'].map(o => <option key={o}>{o}</option>)}</Select><Select aria-label="Filter by status" value={status} onChange={e => setStatus(e.target.value)}>{['All statuses', 'Investigating', 'Identified', 'Monitoring', 'Resolved'].map(o => <option key={o}>{o}</option>)}</Select></div><div {...stylex.props(ui.row)}><ArrowDownWideNarrow size={14} color="#7f8e87" /><Select aria-label="Sort incidents" value={sort} onChange={e => setSort(e.target.value)}>{['Newest first', 'Oldest first', 'Severity'].map(o => <option key={o}>{o}</option>)}</Select><Button icon aria-label="List view" aria-pressed={view === 'list'} variant={view === 'list' ? 'primary' : undefined} onClick={() => setView('list')}><List size={15} /></Button><Button icon aria-label="Board view" aria-pressed={view === 'board'} variant={view === 'board' ? 'primary' : undefined} onClick={() => setView('board')}><Columns3 size={15} /></Button></div></div>
  {view === 'list' ? <Panel noPadding><IncidentTable incidents={filtered} />{!filtered.length && <EmptyResults name="incidents" />}<div {...stylex.props(s.foot)}><span>{filtered.length} of {data.incidents.length} incidents</span><span>All times in UTC</span></div></Panel> : <div {...stylex.props(s.board)}>{['Investigating', 'Identified', 'Monitoring', 'Resolved'].map(status => <section key={status} {...stylex.props(s.column)}><div {...stylex.props(ui.between)}><Status value={status} /><Badge>{filtered.filter(i => i.status === status).length}</Badge></div>{filtered.filter(i => i.status === status).map(i => <div key={i.id} {...stylex.props(s.card)}><div {...stylex.props(ui.between)}><Status value={i.severity} /><span {...stylex.props(ui.mono, ui.muted)}>{i.id}</span></div><AppLink to={`/incidents/${i.id}`} subtle><h3 {...stylex.props(s.title)}>{i.title}</h3></AppLink><p {...stylex.props(ui.small, ui.muted)}>{i.services.join(' · ')}</p><hr {...stylex.props(ui.divider)} /><div {...stylex.props(ui.between)}><AvatarGroup names={[i.commander, ...i.responders]} max={3} /><span {...stylex.props(ui.small, ui.muted)}>{i.duration}</span></div></div>)}</section>)}</div>}</>;
}
export function IncidentTable({ incidents }: { incidents: Incident[] }) {
  return <div {...stylex.props(ui.tableWrap)}><table {...stylex.props(ui.table)}><thead><tr>{['Incident', 'Severity', 'Status', 'Commander', 'Duration', 'Responders'].map(h => <th scope="col" key={h} {...stylex.props(ui.th)}>{h}</th>)}</tr></thead><tbody>{incidents.map(i => <tr key={i.id} {...stylex.props(ui.tr)}><td {...stylex.props(ui.td)}><div {...stylex.props(ui.row, ui.mono, ui.muted)}><ShieldAlert size={12} />{i.id}<span {...stylex.props(ui.tableSub)}>{i.created}</span></div><AppLink to={`/incidents/${i.id}`} subtle><span {...stylex.props(ui.tableTitle)}>{i.title}</span></AppLink><div {...stylex.props(ui.row, ui.tableSub)}>{i.services.slice(0, 2).map(n => <AppLink key={n} to={`/services/${services.find(s => s.name === n)?.slug}`} subtle>{n}</AppLink>)}{i.services.length > 2 && <span>+{i.services.length - 2}</span>}</div></td><td {...stylex.props(ui.td)}><Status value={i.severity} /></td><td {...stylex.props(ui.td)}><Status value={i.status} /></td><td {...stylex.props(ui.td)}><Person name={i.commander} /></td><td {...stylex.props(ui.td)}><span {...stylex.props(ui.row)}><Clock3 size={12} />{i.duration}</span></td><td {...stylex.props(ui.td)}><AvatarGroup names={i.responders} /></td></tr>)}</tbody></table></div>;
}
