import * as stylex from '@stylexjs/stylex';
import { useState } from 'react';
import { ArrowRight, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Headphones, Info, Plus, ShieldCheck, Users } from 'lucide-react';
import { people, teams } from '../data/model';
import { useStore } from '../state/store';
import { AppLink, Avatar, Badge, Button, Field, Input, Modal, PageHeader, Panel, Person, Select, Tabs, ui } from '../components/ui';
const s = stylex.create({
  roster: { display: 'grid', gridTemplateColumns: { default: 'repeat(3, minmax(0, 1fr))', '@media (max-width: 1150px)': 'repeat(2, minmax(0, 1fr))', '@media (max-width: 650px)': '1fr' }, gap: 17, marginBottom: 24 },
  personRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, padding: '13px 0' },
  schedule: { minWidth: 850 },
  scheduleHead: { display: 'grid', gridTemplateColumns: '160px repeat(7, minmax(0, 1fr))', borderBottom: '1px solid #e4ebe6' },
  day: { padding: '14px 8px', textAlign: 'center', borderLeft: '1px solid #edf1ee', fontSize: 10, color: '#8b9c90' },
  dayNumber: { display: 'block', fontSize: 19, fontWeight: 600, marginTop: 4, color: '#5a7261' },
  today: { backgroundColor: '#eff8f2', color: '#1d8153' },
  scheduleRow: { display: 'grid', gridTemplateColumns: '160px minmax(0, 1fr)', borderBottom: '1px solid #e9eeea', minHeight: 92 },
  rowLabel: { padding: '22px 17px', fontSize: 12, fontWeight: 600, borderRight: '1px solid #e6ece7' },
  shifts: { display: 'grid', gridTemplateColumns: 'repeat(7, minmax(0, 1fr))', alignItems: 'center', gap: 5, padding: '18px 6px', backgroundImage: 'linear-gradient(to right, transparent calc(100% - 1px), #edf2ee 0)', backgroundSize: '14.2857% 100%' },
  shift: (start: number, end: number, color: string) => ({ gridColumn: `${start} / ${end}`, backgroundColor: color, borderRadius: 5, padding: '10px 8px', fontSize: 10, display: 'flex', alignItems: 'center', gap: 6, minWidth: 0, color: '#4f6f5b', border: '1px solid #dae8dd' }),
  shiftName: { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  policy: { display: 'flex', gap: 13, alignItems: 'flex-start', padding: '17px 0', borderBottom: '1px solid #e8eeea' },
  step: { width: 27, height: 27, display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: '#ecf5ef', color: '#529068', borderRadius: '50%', flexShrink: 0 },
});
export function OnCall() {
  const { data, setData, notify } = useStore();
  const [week, setWeek] = useState(0); const [view, setView] = useState('Schedule'); const [modal, setModal] = useState<'override' | 'policy' | null>(null); const [teamName, setTeamName] = useState('Payments'); const [engineer, setEngineer] = useState('Elena Rodriguez'); const [reason, setReason] = useState('');
  const days = Array.from({ length: 7 }, (_, i) => new Date(Date.UTC(2026, 8, 7 + week * 7 + i))); const label = `${days[0].toLocaleDateString('en-US', { month: 'short', day: 'numeric', timeZone: 'UTC' })} – ${days[6].toLocaleDateString('en-US', { month: 'short', day: 'numeric', timeZone: 'UTC' })}, 2026`;
  const selectedTeam = teams.find(t => t.name === teamName)!;
  return <><PageHeader title="On-call" description="The right people. Ready when it matters." actions={<><Badge tone="green" dot>All teams covered</Badge><Button variant="primary" onClick={() => setModal('override')}><Plus size={14} />Create override</Button></>} /><div {...stylex.props(ui.callout)}><Clock3 size={17} /><span><strong>Two handoffs coming up today.</strong> Noah Williams joins Platform at 11:38 AM. Elena Rodriguez takes over Payments at 5:00 PM.</span></div><Tabs tabs={['Schedule', 'Current roster', 'Escalation policies']} value={view} onChange={setView} />
  {view === 'Schedule' && <><div {...stylex.props(ui.toolbar)}><div {...stylex.props(ui.row)}><Button icon aria-label="Previous week" onClick={() => setWeek(week - 1)}><ChevronLeft size={15} /></Button><Button icon aria-label="Next week" onClick={() => setWeek(week + 1)}><ChevronRight size={15} /></Button><h2 {...stylex.props(ui.sectionTitle)}>{label}</h2><Button variant="ghost" onClick={() => setWeek(0)}>Today</Button></div><span {...stylex.props(ui.small, ui.muted)}>Weekly view · UTC</span></div><Panel noPadding><div {...stylex.props(ui.tableWrap)}><div {...stylex.props(s.schedule)}><div {...stylex.props(s.scheduleHead)}><div {...stylex.props(s.day)}>TEAM / ROTATION</div>{days.map((d, i) => <div key={i} {...stylex.props(s.day, week === 0 && i === 1 && s.today)}>{d.toLocaleDateString('en-US', { weekday: 'short', timeZone: 'UTC' })}<span {...stylex.props(s.dayNumber)}>{d.getUTCDate()}</span>{week === 0 && i === 1 && <span>Today</span>}</div>)}</div>{teams.map((t, i) => <div key={t.name} {...stylex.props(s.scheduleRow)}><div {...stylex.props(s.rowLabel)}><AppLink to={`/teams/${t.slug}`} subtle>{t.name}</AppLink><p {...stylex.props(ui.tableSub)}>Primary rotation</p></div><div {...stylex.props(s.shifts)}>{[{ start: 1, end: 3, name: week === 0 ? data.overrides[t.name] ?? t.primary : t.secondary }, { start: 3, end: 6, name: week === 0 ? t.next : t.primary }, { start: 6, end: 8, name: week === 0 ? t.secondary : t.next }].map((shift, index) => <button key={index} onClick={() => { setTeamName(t.name); setModal('policy'); }} {...stylex.props(s.shift(shift.start, shift.end, i % 3 === 0 ? '#e8f3ea' : i % 3 === 1 ? '#eaf0f7' : '#f2eef7'))}><Avatar name={shift.name} size={24} /><span {...stylex.props(s.shiftName)}>{shift.name}<span {...stylex.props(ui.tableSub)}> · 09:00 UTC</span></span></button>)}</div></div>)}</div></div><div {...stylex.props(ui.pad, ui.between)}><span {...stylex.props(ui.small, ui.muted)}>Select a shift to see coverage and escalation details.</span><span {...stylex.props(ui.row, ui.small, ui.green)}><ShieldCheck size={13} />No coverage gaps</span></div></Panel><div {...stylex.props(ui.grid2)}><Panel title="Upcoming handoffs"><div {...stylex.props(s.personRow)}><Person name="Noah Williams" subtitle="Platform · Secondary rotation" /><Badge>Today, 11:38 AM</Badge></div><div {...stylex.props(s.personRow)}><Person name="Elena Rodriguez" subtitle="Payments · Primary rotation" /><Badge>Today, 5:00 PM</Badge></div></Panel><Panel title="Coverage at a glance"><div {...stylex.props(s.personRow)}><span>Primary coverage</span><Badge tone="green">100% · All 5 teams</Badge></div><div {...stylex.props(s.personRow)}><span>Secondary coverage</span><Badge tone="green">100% · All 5 teams</Badge></div><p {...stylex.props(ui.small, ui.secondary)}>Shifts use a follow-the-sun handoff. The outgoing engineer stays available until the incoming engineer acknowledges.</p></Panel></div></>}
  {view === 'Current roster' && <div {...stylex.props(s.roster)}>{teams.map(t => <Panel key={t.name} title={t.name} aside={<Badge tone="green" dot>Covered</Badge>}><div {...stylex.props(s.personRow)}><Person name={data.overrides[t.name] ?? t.primary} subtitle="Primary engineer" /></div><div {...stylex.props(s.personRow)}><Person name={t.secondary} subtitle="Secondary engineer" /></div><hr {...stylex.props(ui.divider)} /><div {...stylex.props(ui.stackSmall)}><span {...stylex.props(ui.small, ui.muted)}>Shift: Mon 9:00 AM → Wed 9:00 AM · 48 hours</span><Person name={t.next} subtitle="Next on call" /><Button onClick={() => { setTeamName(t.name); setModal('policy'); }}>Escalation policy <ArrowRight size={13} /></Button></div></Panel>)}</div>}
  {view === 'Escalation policies' && <div {...stylex.props(ui.stack)}>{teams.map(t => <Panel key={t.name} title={`${t.name} escalation`} aside={<Button onClick={() => { setTeamName(t.name); setModal('policy'); }}>View policy</Button>}><div {...stylex.props(ui.row, ui.wrap)}><Badge tone="green">Immediately</Badge><Person name={data.overrides[t.name] ?? t.primary} subtitle="Primary" /><ArrowRight size={14} /><Badge>After 5 minutes</Badge><Person name={t.secondary} subtitle="Secondary" /><ArrowRight size={14} /><Badge>After 15 minutes</Badge><Person name={t.lead} subtitle="Team lead" /></div></Panel>)}</div>}
  {modal === 'override' && <Modal title="Create an on-call override" onClose={() => setModal(null)} footer={<Button variant="primary" disabled={!reason.trim()} onClick={() => { setData(d => ({ ...d, overrides: { ...d.overrides, [teamName]: engineer } })); notify(`${engineer} is now covering ${teamName} for this shift`); setModal(null); }}>Confirm override</Button>}><div {...stylex.props(ui.stack)}><div {...stylex.props(ui.callout)}><Info size={17} />This override replaces the primary engineer for the current shift. Your team’s normal rotation stays unchanged.</div><Field label="Team"><Select value={teamName} onChange={e => setTeamName(e.target.value)}>{teams.map(t => <option key={t.name}>{t.name}</option>)}</Select></Field><Field label="Covering engineer"><Select value={engineer} onChange={e => setEngineer(e.target.value)}>{people.map(p => <option key={p.name}>{p.name}</option>)}</Select></Field><Field label="Reason *"><Input value={reason} onChange={e => setReason(e.target.value)} placeholder="e.g. Covering a planned absence" /></Field><p {...stylex.props(ui.small, ui.muted)}>Effective now until Wednesday, September 9 at 9:00 AM UTC.</p></div></Modal>}
  {modal === 'policy' && <Modal title={`${teamName} · Escalation policy`} onClose={() => setModal(null)} footer={<Button variant="primary" onClick={() => { notify(`Demo page sent to ${data.overrides[teamName] ?? selectedTeam.primary}`); setModal(null); }}><Headphones size={14} />Page on-call engineer</Button>}><div {...stylex.props(ui.callout)}><ShieldCheck size={17} />24/7 coverage · Repeat policy twice if no engineer acknowledges.</div>{[{ person: data.overrides[teamName] ?? selectedTeam.primary, time: 'Immediately', role: 'Primary on call' }, { person: selectedTeam.secondary, time: 'After 5 minutes', role: 'Secondary engineer' }, { person: selectedTeam.lead, time: 'After 15 minutes', role: 'Team lead' }].map((step, i) => <div key={i} {...stylex.props(s.policy)}><span {...stylex.props(s.step)}>{i + 1}</span><div {...stylex.props(ui.grow)}><p {...stylex.props(ui.small, ui.muted)}>{step.time}</p><Person name={step.person} subtitle={step.role} /></div><Badge>Push + SMS</Badge></div>)}</Modal>}
  </>;
}
