/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts.index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments.index'
import { Route as IncidentsIndexRouteImport } from './routes/incidents.index'
import { Route as IncidentsIncidentIdRouteImport } from './routes/incidents.$incidentId'
import { Route as OnCallIndexRouteImport } from './routes/on-call.index'
import { Route as PostmortemsIndexRouteImport } from './routes/postmortems.index'
import { Route as PostmortemsPostmortemIdRouteImport } from './routes/postmortems.$postmortemId'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: '/incidents/$incidentId',
  path: '/incidents/$incidentId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnCallIndexRoute = OnCallIndexRouteImport.update({
  id: '/on-call/',
  path: '/on-call/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostmortemsIndexRoute = PostmortemsIndexRouteImport.update({
  id: '/postmortems/',
  path: '/postmortems/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostmortemsPostmortemIdRoute = PostmortemsPostmortemIdRouteImport.update({
  id: '/postmortems/$postmortemId',
  path: '/postmortems/$postmortemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/postmortems/$postmortemId': typeof PostmortemsPostmortemIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/on-call/': typeof OnCallIndexRoute
  '/postmortems/': typeof PostmortemsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/postmortems/$postmortemId': typeof PostmortemsPostmortemIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/alerts': typeof AlertsIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/incidents': typeof IncidentsIndexRoute
  '/on-call': typeof OnCallIndexRoute
  '/postmortems': typeof PostmortemsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/postmortems/$postmortemId': typeof PostmortemsPostmortemIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/on-call/': typeof OnCallIndexRoute
  '/postmortems/': typeof PostmortemsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/incidents/$incidentId'
    | '/postmortems/$postmortemId'
    | '/services/$serviceId'
    | '/teams/$teamId'
    | '/alerts/'
    | '/analytics/'
    | '/deployments/'
    | '/incidents/'
    | '/on-call/'
    | '/postmortems/'
    | '/services/'
    | '/settings/'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/incidents/$incidentId'
    | '/postmortems/$postmortemId'
    | '/services/$serviceId'
    | '/teams/$teamId'
    | '/alerts'
    | '/analytics'
    | '/deployments'
    | '/incidents'
    | '/on-call'
    | '/postmortems'
    | '/services'
    | '/settings'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/incidents/$incidentId'
    | '/postmortems/$postmortemId'
    | '/services/$serviceId'
    | '/teams/$teamId'
    | '/alerts/'
    | '/analytics/'
    | '/deployments/'
    | '/incidents/'
    | '/on-call/'
    | '/postmortems/'
    | '/services/'
    | '/settings/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
  PostmortemsPostmortemIdRoute: typeof PostmortemsPostmortemIdRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  OnCallIndexRoute: typeof OnCallIndexRoute
  PostmortemsIndexRoute: typeof PostmortemsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$incidentId': {
      id: '/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/on-call/': {
      id: '/on-call/'
      path: '/on-call'
      fullPath: '/on-call/'
      preLoaderRoute: typeof OnCallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postmortems/': {
      id: '/postmortems/'
      path: '/postmortems'
      fullPath: '/postmortems/'
      preLoaderRoute: typeof PostmortemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postmortems/$postmortemId': {
      id: '/postmortems/$postmortemId'
      path: '/postmortems/$postmortemId'
      fullPath: '/postmortems/$postmortemId'
      preLoaderRoute: typeof PostmortemsPostmortemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
  PostmortemsPostmortemIdRoute: PostmortemsPostmortemIdRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  OnCallIndexRoute: OnCallIndexRoute,
  PostmortemsIndexRoute: PostmortemsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
